# Global settings applied to the whole site
[build]
  # Directory to use as the build output directory
  publish = "build"
  
# Use 200 redirect pattern for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 